version: "2"

services:
  ipfs:
    image: ipfs/kubo
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "8080"
      - "5001:5001"
    networks:
      - dummy

  dummy:
    image: dummy-dummy:latest
    build:
      context: .
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:5223"
    ports:
      - "5223"
    networks:
      - dummy
    healthcheck:
      test: curl --fail http://localhost:5223/health || exit 1
      interval: 3s
      timeout: 60s
      start_period: 3s

  nginx:
    image: nginx:1.25.3-alpine3.18-slim
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./truquest.crt:/etc/nginx/ssl/truquest.crt
      - ./truquest.key:/etc/nginx/ssl/truquest.key
      - ./static_files:/static_files
    ports:
      - "443:443"
    networks:
      - dummy
    depends_on:
      dummy:
        condition: service_healthy

networks:
  dummy:
    driver: bridge
