version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181'
    networks:
      - dummy
    restart: unless-stopped

  kafka-1:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - '9092:9092'
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CREATE_TOPICS: 'testtest:1:1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dummy
    restart: unless-stopped

  debezium:
    image: debezium/connect
    environment:
      BOOTSTRAP_SERVERS: 'kafka-1:9092'
      GROUP_ID: debez
      CONFIG_STORAGE_TOPIC: debez_connect_configs
      OFFSET_STORAGE_TOPIC: debez_connect_offsets
      STATUS_STORAGE_TOPIC: debez_connect_statuses
    ports:
      - '8083:8083'
    networks:
      - dummy
    depends_on:
      - zookeeper
      - kafka-1

  kafka-ui:
    image: provectuslabs/kafka-ui
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092
    ports:
      - '7777:8080'
    networks:
      - dummy
    depends_on:
      - zookeeper
      - kafka-1

networks:
  dummy:
    driver: bridge
