FROM ubuntu:focal

RUN apt-get update && apt-get install -y wget curl

RUN wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb
RUN apt-get update && apt-get install -y aspnetcore-runtime-7.0

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs
RUN npm i -g playwright@1.39.0 && npx playwright install --with-deps chromium
RUN apt-get remove nodejs -y

COPY ublock/ /ublock/
COPY isdcac/ /isdcac/